"""Translate a Dogwood policy file into the TLA+ policy data a spec can check.

The point, and it is the same one `graph_to_tla.py` makes about Strands graphs. A model of a policy
written by reading the policy is a paraphrase, and nothing checks a paraphrase. Here the policy text
IS the input: it goes through `dogwood_parse`, the same parser whose reading agrees with the
reference implementation on 776 corpus cases, and out the other side as the records
`DogwoodSemantics!Decide` evaluates.

    rotation_*.dw ──> dogwood_parse ──> RotationPolicies.tla ──┐
                                                               ├──> TLC checks the properties
                                 SessionRotation.tla ──────────┘

So `SessionRotation.tla` no longer hand-writes the policy it is reasoning about. That was the last
gap in that spec: the decision came from a corpus-validated evaluator, but nothing said the records
it evaluated meant what the comment above them claimed.

The generated module is checked in, and `SpecTests` regenerates it and compares — a `.dw` edit that
is not carried through shows up as a failure rather than as a spec quietly checking the old policy.

    python tests/strands/dw_to_tla.py            # rewrite the generated module
    python tests/strands/dw_to_tla.py --check    # fail if it is out of date
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

REPO = Path(__file__).resolve().parents[2]
SPECS = REPO / "specs" / "policy" / "TemporalPolicy"
GENERATED = SPECS / "RotationPolicies.tla"

from dogwood_differential import tla_cond  # noqa: E402
from dogwood_parse import Unsupported, parse_policies  # noqa: E402

SOURCES = {
    "AggregatePolicies": "rotation_aggregate.dw",
    "ApprovalPolicies": "rotation_approval.dw",
}


def policy_seq(policies: list[dict]) -> str:
    return ",\n".join(
        f'    [effect |-> "{p["effect"]}", action |-> "{p["action"]}", cond |-> {tla_cond(p["cond"])}]'
        for p in policies)


def cap_of(policies: list[dict]) -> int:
    """The bound the aggregate forbid compares against — the cap the policy actually states.

    Taken from the policy rather than set beside it in a .cfg, so the property TLC checks is
    stated over the same number the policy text contains. Two places to change it is one too many.
    """
    caps = [p["cond"]["value"] for p in policies if p["cond"]["op"] == "agg"]
    if len(caps) != 1:
        raise Unsupported(f"expected exactly one aggregate policy, found {len(caps)}")
    return caps[0]


def generate() -> str:
    sets, cap = {}, None
    for name, filename in SOURCES.items():
        policies = parse_policies((SPECS / filename).read_text(encoding="utf-8"))
        sets[name] = policy_seq(policies)
        if any(p["cond"]["op"] == "agg" for p in policies):
            cap = cap_of(policies)

    if cap is None:
        raise Unsupported("no aggregate policy found, so there is no cap to check against")

    bodies = "\n\n".join(f"{name} ==\n  <<\n{seq}\n  >>" for name, seq in sets.items())

    return f"""\\* GENERATED by tests/strands/dw_to_tla.py -- do not edit. Regenerate instead.
\\*
\\* Translated from {', '.join(sorted(SOURCES.values()))} by the same parser that agrees with the
\\* Dogwood reference implementation on 776 recorded corpus cases. SessionRotation.tla checks these
\\* policies rather than a hand-written approximation of them.
---------------------------- MODULE RotationPolicies ----------------------------
EXTENDS Integers, Sequences

\\* The bound the aggregate policy states, lifted out of the policy text so the property and the
\\* rule cannot disagree about what the cap is.
Cap == {cap}

{bodies}

=============================================================================
"""


def main() -> int:
    text = generate()

    if "--check" in sys.argv:
        current = GENERATED.read_text(encoding="utf-8") if GENERATED.exists() else ""
        if current != text:
            print(f"{GENERATED.name} is out of date with the .dw sources.\n"
                  "Regenerate with:  python tests/strands/dw_to_tla.py", file=sys.stderr)
            return 1
        print(f"{GENERATED.name} is up to date")
        return 0

    GENERATED.write_text(text, encoding="utf-8")
    print(f"wrote {GENERATED.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
