"""Translate a Strands agent graph into the TLA+ the DependencyDAG properties are stated over.

The point. Verifying a workflow means having a model of it, and a model written by reading code is a
paraphrase that nothing checks. But a Strands `Graph` is not a description of a workflow — it *is*
the workflow, built with `GraphBuilder` and executed as-is. Walking that object is therefore
translation, not inference: the thing we model and the thing that runs cannot drift apart, because
they are the same object.

    GraphBuilder ──> Graph ──> Workflow.tla ──┐
                                              ├──> TLC checks HP10 + termination
                       DependencyDAG.tla ─────┘

Only the DAG is generated. The properties and the transition logic live once in DependencyDAG.tla,
which EXTENDS the generated module — so a new workflow is checked against the same reviewed
properties without anyone rewriting them.

There is no DOT or mermaid export in the SDK to translate instead; the mermaid blocks in the Strands
docs are hand-drawn illustrations. The object graph is the artifact, and it is the better one — no
format, no parser, nothing to fall out of step.

    python tests/strands/graph_to_tla.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from shared_budget import ScriptedModel  # noqa: E402

from strands import Agent  # noqa: E402
from strands.multiagent import GraphBuilder  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
SPECS = REPO / "specs" / "DependencyDAG"
JAR = REPO / "lib" / "tla2tools-1.7.4.jar"


def build_example_graph():
    """The workflow from the Strands graph documentation.

    research ──┬──> analysis ───┐
               └──> factcheck ──┴──> report
    """

    def agent(name: str) -> Agent:
        return Agent(model=ScriptedModel(cost=1), system_prompt=name, callback_handler=None)

    builder = GraphBuilder()
    for name in ("research", "analysis", "factcheck", "report"):
        builder.add_node(agent(name), name)

    builder.add_edge("research", "analysis")
    builder.add_edge("research", "factcheck")
    builder.add_edge("analysis", "report")
    builder.add_edge("factcheck", "report")
    builder.set_entry_point("research")

    return builder.build()


def to_tla(graph) -> str:
    """Emit the Tasks and Deps definitions DependencyDAG.tla expects.

    `GraphNode.dependencies` is already the parent set the properties are stated over, so this is a
    rename rather than an interpretation — the one place a translator could go wrong is narrow
    enough to read at a glance.
    """
    nodes = sorted(graph.nodes)
    deps = {n: sorted(d.node_id for d in graph.nodes[n].dependencies) for n in nodes}

    tasks = ", ".join('"{}"'.format(n) for n in nodes)

    arms = [
        '        [] t = "{}" -> {{{}}}'.format(n, ", ".join('"{}"'.format(p) for p in deps[n]))
        for n in nodes
        if deps[n]
    ]
    arms.append("        [] OTHER    -> {}")
    arms[0] = arms[0].replace("        [] ", "        CASE ", 1)  # CASE's first arm has no []

    lines = [
        r"\* GENERATED by tests/strands/graph_to_tla.py from a live Strands Graph.",
        r"\* Do not edit. Regenerate instead.",
        "------------------------------- MODULE Workflow -------------------------------",
        "",
        "Tasks == {{{}}}".format(tasks),
        "",
        "Deps ==",
        r"    [t \in Tasks |->",
        "\n".join(arms) + "]",
        "",
        "=============================================================================",
        "",
    ]
    return "\n".join(lines)


def check(workflow_tla: str, spec: str) -> tuple[bool, str]:
    """Run one DependencyDAG spec against the generated workflow, in a scratch directory.

    Copied out rather than run in place so a generated Workflow.tla never overwrites the
    hand-written one the checked-in specs are verified against.
    """
    with tempfile.TemporaryDirectory(prefix="anchor-graph-") as tmp:
        work = Path(tmp)
        for name in (f"{spec}.tla", f"{spec}.cfg"):
            shutil.copy(SPECS / name, work / name)
        (work / "Workflow.tla").write_text(workflow_tla, encoding="utf-8")

        proc = subprocess.run(
            ["java", "-cp", str(JAR), "tlc2.TLC", "-cleanup",
             "-metadir", str(work / "states"), "-config", f"{spec}.cfg", f"{spec}.tla"],
            cwd=work, capture_output=True, text=True,
        )
        return proc.returncode == 0, proc.stdout + proc.stderr


def main() -> int:
    graph = build_example_graph()
    print(f"built a Strands graph: {len(graph.nodes)} nodes, {len(graph.edges)} edges")
    for name in sorted(graph.nodes):
        deps = sorted(d.node_id for d in graph.nodes[name].dependencies)
        print(f"    {name:10} depends on {deps or '(entry point)'}")

    workflow = to_tla(graph)
    print("\ngenerated Workflow.tla:\n")
    print("\n".join("    " + line for line in workflow.strip().splitlines()[2:-1]))

    ok, output = check(workflow, "DependencyDAG")
    print(f"\nHP10 + termination on this workflow: {'HOLD' if ok else 'VIOLATED'}")
    if not ok:
        print(output[-1200:])
        return 1

    # The same workflow against the variant that omits orphan cancellation. It must fail, or the
    # generated DAG is too trivial to tell the two apart and the check above proves nothing.
    broken, _ = check(workflow, "Bug5_NoFailurePropagation")
    print(f"without failure propagation:         {'HOLD (!)' if broken else 'VIOLATED, as expected'}")
    if broken:
        print("  the generated graph has no failure path to strand; it does not exercise the property")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
