"""Our CIDR containment against Python's `ipaddress` module.

EVERY OTHER PART OF THE DOGWOOD MODEL IS CHECKED AGAINST DOGWOOD. This one cannot be, and the
reason is worth stating rather than working around:

  * `ip(` and `isInRange` appear in **zero** `.dw` files across the whole Dogwood tree -- no corpus
    case, no documentation example, no test. There is nothing recorded to check against.
  * `dogwood replay` cannot supply an address at all. Its log value parser
    (`interpreter/log_parse.rs::parse_value_depth`) handles null, bool, array, object, entity ref,
    quoted string, int and decimal, then falls through to "bare token as string" -- there is no
    case for an extension value. So `ip("10.1.2.3")` in a trace becomes the STRING `ip("10.1.2.3")`,
    the extension call fails on the wrong type, and the policy silently does not apply.

    Measured: a forbid on `isInRange(ip("10.0.0.0/8"))` ALLOWS 10.1.2.3, while the same policy
    shape on `port == 22` correctly denies. The control is what makes that mean something -- the
    trace is read fine; the address is what cannot travel.

So the oracle is Python's `ipaddress`, a battle-tested implementation of the same standard. That is
a real differential -- two independent implementations of one spec -- and it validates the
ARITHMETIC only. It says nothing about how AgentCore feeds an address into a policy, which is
exactly the part Dogwood's own tooling cannot exercise either.

    python tests/strands/ip_differential.py

Needs the venv and the TLA+ jar; no network, no engine.
"""

from __future__ import annotations

import ipaddress
import random
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SPECS = REPO / "specs" / "policy" / "TemporalPolicy"

sys.path.insert(0, str(REPO / "src"))

from translator import find_jar, parse_cidr  # noqa: E402

# Prefixes chosen to land on and off byte boundaries: /8 /16 /24 /32 exercise the whole-octet path,
# /0 /9 /10 /12 /22 /23 /25 /26 /31 the partial-octet division that is the only arithmetic here.
CIDRS = ["10.0.0.0/8", "192.168.1.0/24", "172.16.0.0/12", "208.4.4.0/22",
         "0.0.0.0/0", "255.255.255.255/32", "127.0.0.1/32", "100.64.0.0/10",
         "10.10.10.0/23", "8.8.8.8/31", "203.0.113.0/26", "198.51.100.128/25",
         "10.0.0.0/9", "169.254.0.0/16", "224.0.0.0/4"]


def cases(seed: int = 20260911) -> list[tuple]:
    """Boundary addresses for each CIDR, plus noise. The boundaries are where range bugs live."""
    rand = random.Random(seed)
    out = []
    for cidr in CIDRS:
        net = ipaddress.ip_network(cidr, strict=False)
        picks = [str(net.network_address), str(net.broadcast_address)]
        if int(net.network_address) > 0:
            picks.append(str(ipaddress.ip_address(int(net.network_address) - 1)))
        if int(net.broadcast_address) < 2 ** 32 - 1:
            picks.append(str(ipaddress.ip_address(int(net.broadcast_address) + 1)))
        picks += [".".join(str(rand.randint(0, 255)) for _ in range(4)) for _ in range(6)]

        octets, prefix = parse_cidr(cidr)
        for a in picks:
            out.append((a, [int(x) for x in a.split(".")], octets, prefix,
                        ipaddress.ip_address(a) in net))
    return out


def module(pairs: list[tuple]) -> str:
    body = "\n".join(
        f'       /\\ IF InRange(<<{", ".join(map(str, addr))}>>, '
        f'<<{", ".join(map(str, net))}>>, {prefix}) = {"TRUE" if exp else "FALSE"}\n'
        f'          THEN TRUE\n'
        f'          ELSE Print(<<"DISAGREE", "{a}", '
        f'"{".".join(map(str, net))}/{prefix}", "ipaddress says", '
        f'{"TRUE" if exp else "FALSE"}>>, FALSE)'
        for a, addr, net, prefix, exp in pairs)

    return f"""\\* GENERATED by tests/strands/ip_differential.py -- do not edit.
---- MODULE IpCheck ----
EXTENDS Integers, Sequences, TLC

\\* DogwoodSemantics takes the corpus cases as a parameter and this module checks none of them;
\\* only `InRange` is under test, and it reads neither.
Cases == << >>
D == INSTANCE DogwoodSemantics
InRange(a, n, p) == D!InRange(a, n, p)

ASSUME /\\ TRUE
{body}
====
"""


def main() -> int:
    pairs = cases()
    print(f"{len(pairs)} (address, CIDR) pairs over {len(CIDRS)} prefixes\n")

    with tempfile.TemporaryDirectory(prefix="anchor-ipdiff-") as tmp:
        work = Path(tmp)
        (work / "IpCheck.tla").write_text(module(pairs), encoding="utf-8")
        (work / "IpCheck.cfg").write_text("", encoding="utf-8")
        shutil.copyfile(SPECS / "DogwoodSemantics.tla", work / "DogwoodSemantics.tla")

        proc = subprocess.run(
            ["java", f"-Djava.io.tmpdir={work}", "-cp", str(find_jar()), "tlc2.TLC",
             "-cleanup", "-metadir", str(work / "states"), "-config", "IpCheck.cfg", "IpCheck.tla"],
            cwd=work, capture_output=True, text=True)
        out = proc.stdout + proc.stderr

    bad = [line.strip() for line in out.splitlines() if "DISAGREE" in line]
    if bad:
        print("DISAGREEMENTS -- our containment differs from ipaddress:")
        for line in bad[:10]:
            print(f"  {line}")
        return 1

    if "Error" in out:
        print("TLC could not answer:", file=sys.stderr)
        print("\n".join(out.splitlines()[-15:]), file=sys.stderr)
        return 1

    print("AGREE on every pair.\n")
    print("This validates the arithmetic and nothing else. Dogwood exercises `isInRange` in no\n"
          "policy anywhere, and its replay path cannot carry an address, so there is no oracle\n"
          "for how a real deployment would feed one in.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
