"""Model-check an arbitrary Dogwood policy file for vacuity, one permit at a time.

    python tests/strands/vacuity.py tests/policies/approval_gate_response.dw

A permit is VACUOUS when no session can make it grant anything. That is not a weak control, it is
zero control, and nothing about the policy's text says so -- it parses, it validates, and it
authorizes nothing. AWS's own material says the automated-reasoning tools Cedar provides do not
answer this for the temporal part of the language.

WHAT MAKES THIS MORE THAN A DEMO. Nobody hand-writes a model of the policy. The `.dw` text goes
through `dogwood_parse` -- the parser whose reading agrees with the reference implementation on 767
recorded corpus pairs -- into a generated `PolicyUnderTest.tla`, and `Vacuity.tla` evaluates it with
`DogwoodSemantics!Decide`, the same evaluator validated against those pairs and against the live
engine on the `error`-event scenarios.

    any .dw ──> dogwood_parse ──> PolicyUnderTest.tla ──┐
                                                        ├──> TLC, once per permit
                              Vacuity.tla ──────────────┘

READ THE RESULT BACKWARDS. TLA+ has no `EF`, so reachability is asked by checking the negation and
reading the counterexample as the witness. A TLC *violation* means the permit CAN grant -- the good
outcome. A clean run means it never does. This script inverts that before printing, because the raw
reading is a trap.

The bound is real: VACUOUS means "no session of up to `--attempts` attempts makes it fire", not
"never". Raise it to trade runtime for confidence.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

REPO = Path(__file__).resolve().parents[2]
SPECS = REPO / "specs" / "policy" / "TemporalPolicy"

from _toolchain import find_jar  # noqa: E402
from dogwood_differential import tla_cond  # noqa: E402
from dogwood_parse import Unsupported, parse_policies  # noqa: E402

# Event kinds AgentCore records. `request` is the decision event -- the point authorization runs --
# and the outcome is `response` when the action completed, `error` when it was denied.
KINDS = ["request", "response", "error"]
DECISION_KIND = "request"


# ---------------------------------------------------------------------------- vocabulary
def walk(node, seen: dict) -> None:
    """Collect the vocabulary a policy actually reads, so nothing unused is modelled."""
    if not isinstance(node, dict):
        return

    if pred := node.get("pred"):
        if pred.get("action"):
            seen["actions"].add(pred["action"])
        if pred.get("kind"):
            seen["kinds"].add(pred["kind"])
        for b in pred.get("binds", []):
            seen["input" if b["side"] == "input" else "output"].add(b["field"])

    for key in ("term", "atom", "left", "cond", "agg"):
        walk(node.get(key), seen)
    for child in node.get("args", []) or []:
        walk(child, seen)


def vocabulary(policies: list[dict]) -> dict:
    seen = {"actions": set(), "kinds": set(), "input": set(), "output": set()}
    for p in policies:
        seen["actions"].add(p["action"])
        walk(p["cond"], seen)

    # Refuse rather than approximate. Every input field shares one numeric domain below, so with
    # two of them the model cannot set them independently and would silently UNDER-explore --
    # reporting "vacuous" for a permit that a state we never visited would have fired. A false
    # "vacuous" is the one wrong answer this tool must not give.
    if len(seen["input"]) > 1:
        raise Unsupported(
            f"policy reads {len(seen['input'])} input fields ({', '.join(sorted(seen['input']))}); "
            "the model gives every input field one shared domain, so this would under-explore")

    unknown = seen["kinds"] - set(KINDS)
    if unknown:
        raise Unsupported(f"event kinds outside AgentCore's convention: {', '.join(sorted(unknown))}")

    return seen


def tla_set(names) -> str:
    return "{" + ", ".join(f'"{n}"' for n in sorted(names)) + "}"


def generate(source: Path, policies: list[dict], vocab: dict) -> str:
    body = ",\n".join(
        f'    [effect |-> "{p["effect"]}", action |-> "{p["action"]}", cond |-> {tla_cond(p["cond"])}]'
        for p in policies)

    return f"""\\* GENERATED by tests/strands/vacuity.py from {source.name} -- do not edit.
\\*
\\* Translated by the parser that agrees with the Dogwood reference implementation on 700 recorded
\\* corpus pairs. Vacuity.tla checks THESE records, so what is model-checked is the policy as
\\* written rather than as paraphrased.
---------------------------- MODULE PolicyUnderTest ----------------------------
EXTENDS Integers, Sequences

Source == "{source.name}"

\\* The vocabulary is lifted from the policy text: only actions, event kinds and input/output
\\* fields some condition actually reads are modelled. A policy that joins on nothing costs nothing.
Actions      == {tla_set(vocab["actions"])}
Kinds        == {tla_set(vocab["kinds"] | {DECISION_KIND})}
InputFields  == {tla_set(vocab["input"])}
OutputFields == {tla_set(vocab["output"])}
DecisionKind == "{DECISION_KIND}"

Policies ==
  <<
{body}
  >>

=============================================================================
"""


# ---------------------------------------------------------------------------- checking
CONFIG = """SPECIFICATION Spec

\\* A session ends after MaxAttempts, which has no successor action.
CHECK_DEADLOCK FALSE

CONSTANTS
    MaxAttempts = {attempts}
    MaxAmount = {amount}
    Target = {target}

INVARIANT TypeOK

\\* MEANT TO FAIL. A violation is the witness session proving this permit can grant
\\* something; a clean run means it never does. See the header of Vacuity.tla.
INVARIANT NeverFires
"""


def check_one(work: Path, target: int, attempts: int, amount: int) -> tuple[bool, str]:
    """Returns (permit can fire, TLC output). Raises if TLC could not answer."""
    (work / "Vacuity.cfg").write_text(
        CONFIG.format(attempts=attempts, amount=amount, target=target), encoding="utf-8")

    proc = subprocess.run(
        ["java", "-cp", str(find_jar()), "tlc2.TLC", "-cleanup",
         "-metadir", str(work / "states"), "-config", "Vacuity.cfg", "Vacuity.tla"],
        cwd=work, capture_output=True, text=True)
    out = proc.stdout + proc.stderr

    if "Invariant NeverFires is violated" in out:
        return True, out
    if proc.returncode == 0 and "Model checking completed" in out:
        return False, out

    # Anything else -- a parse error, an unsupported construct reaching TLC, a TypeOK failure --
    # is not an answer. Never let it read as "vacuous"; that is the silent-wrong-answer direction.
    raise RuntimeError(f"TLC could not answer for permit {target}:\n{out}")


def witness(out: str) -> str:
    """The session TLC found, as the actions attempted in order.

    Only the LAST state block is scanned. TLC prints the whole `trace` variable at every state, so
    each event appears once more for every state that follows it -- reading the full output turns a
    two-attempt witness into "Approve -> Approve -> Trade" and overstates what it took to fire.
    """
    states = re.split(r"^State \d+: ", out, flags=re.MULTILINE)
    final = states[-1] if len(states) > 1 else out
    actions = re.findall(r'action \|-> "([A-Za-z0-9_]+)",\s*kind \|-> "' + DECISION_KIND + '"', final)
    return " -> ".join(actions) if actions else "(see TLC output, --verbose)"


# ---------------------------------------------------------------------------- entry
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("policy", type=Path, help="a .dw policy file")
    ap.add_argument("--attempts", type=int, default=3, help="session length bound (default 3)")
    ap.add_argument("--amount", type=int, default=2,
                    help="numeric domain for input fields, 1..N (default 2)")
    ap.add_argument("--verbose", action="store_true", help="print the TLC output for each permit")
    args = ap.parse_args()

    if not args.policy.exists():
        print(f"no such policy file: {args.policy}", file=sys.stderr)
        return 2

    try:
        policies = parse_policies(args.policy.read_text(encoding="utf-8"))
        vocab = vocabulary(policies)
    except Unsupported as e:
        # The house rule: refuse rather than approximate. A translator that quietly mishandles a
        # construct produces a verdict nobody can attribute.
        print(f"REFUSED: {args.policy.name} is outside the modelled subset\n  {e}", file=sys.stderr)
        return 2

    permits = [i + 1 for i, p in enumerate(policies) if p["effect"] == "permit"]
    forbids = len(policies) - len(permits)

    print(f"{args.policy.name}: {len(permits)} permit(s), {forbids} forbid(s), "
          f"bound {args.attempts} attempts\n")

    if not permits:
        print("nothing to check -- a file with no permit grants nothing by construction")
        return 0

    vacuous = []
    with tempfile.TemporaryDirectory(prefix="anchor-vacuity-") as tmp:
        work = Path(tmp)
        (work / "PolicyUnderTest.tla").write_text(
            generate(args.policy, policies, vocab), encoding="utf-8")
        for module in ("Vacuity.tla", "DogwoodSemantics.tla"):
            shutil.copyfile(SPECS / module, work / module)

        for i in permits:
            fires, out = check_one(work, i, args.attempts, args.amount)
            p = policies[i - 1]
            label = f'permit #{i}  action == {p["action"]}'

            if fires:
                print(f"  {label:34} live      witness: {witness(out)}")
            else:
                print(f"  {label:34} VACUOUS   no session of up to {args.attempts} "
                      "attempts makes it grant")
                vacuous.append(i)

            if args.verbose:
                print("\n".join(f"      {line}" for line in out.splitlines()))

    print()
    if vacuous:
        print(f"{len(vacuous)} vacuous permit(s): {', '.join(f'#{i}' for i in vacuous)}.\n"
              "A vacuous permit authorizes nothing. If it is the control someone is relying on,\n"
              "the capability it was meant to grant is unreachable -- and if it is a gate someone\n"
              "is relying on, whatever it guards is protected by accident rather than by design.")
    else:
        print(f"every permit can grant something within {args.attempts} attempts.\n"
              "That is not a proof of correctness -- only that none of them is inert.")

    # Vacuity is a finding, not an error. The exit code says whether the run ANSWERED.
    return 0


if __name__ == "__main__":
    sys.exit(main())
