\* GENERATED by tests/strands/cedar_differential.py -- do not edit.
\* Policies translated from policies.cedar; Oracle measured from the real cedarpy engine.
---------------------------- MODULE CedarDifferential ----------------------------
EXTENDS Naturals, Sequences, TLC

PrincipalSet == {[type |-> "User", id |-> "alice"], [type |-> "User", id |-> "bob"], [type |-> "Admin", id |-> "root"]}
ActionSet == {"search", "read_file", "delete_file", "send_email"}
CallCountSet == {0, 1, 2, 3, 4}

Policies ==
  <<
    [effect |-> "permit", principal |-> [kind |-> "any"], action |-> [kind |-> "eq", name |-> "search"], conditions |-> <<>>],
    [effect |-> "permit", principal |-> [kind |-> "any"], action |-> [kind |-> "eq", name |-> "read_file"], conditions |-> <<[op |-> "lt", value |-> 3]>>],
    [effect |-> "permit", principal |-> [kind |-> "eq", entity |-> [type |-> "Admin", id |-> "root"]], action |-> [kind |-> "any"], conditions |-> <<>>],
    [effect |-> "forbid", principal |-> [kind |-> "any"], action |-> [kind |-> "eq", name |-> "delete_file"], conditions |-> <<>>]
  >>

Oracle ==
  (
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "delete_file", callCount |-> 0] :> "Deny" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "delete_file", callCount |-> 1] :> "Deny" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "delete_file", callCount |-> 2] :> "Deny" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "delete_file", callCount |-> 3] :> "Deny" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "delete_file", callCount |-> 4] :> "Deny" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "read_file", callCount |-> 0] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "read_file", callCount |-> 1] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "read_file", callCount |-> 2] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "read_file", callCount |-> 3] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "read_file", callCount |-> 4] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "search", callCount |-> 0] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "search", callCount |-> 1] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "search", callCount |-> 2] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "search", callCount |-> 3] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "search", callCount |-> 4] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "send_email", callCount |-> 0] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "send_email", callCount |-> 1] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "send_email", callCount |-> 2] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "send_email", callCount |-> 3] :> "Allow" @@
    [principal |-> [type |-> "Admin", id |-> "root"], action |-> "send_email", callCount |-> 4] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "delete_file", callCount |-> 0] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "delete_file", callCount |-> 1] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "delete_file", callCount |-> 2] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "delete_file", callCount |-> 3] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "delete_file", callCount |-> 4] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "read_file", callCount |-> 0] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "read_file", callCount |-> 1] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "read_file", callCount |-> 2] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "read_file", callCount |-> 3] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "read_file", callCount |-> 4] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "search", callCount |-> 0] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "search", callCount |-> 1] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "search", callCount |-> 2] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "search", callCount |-> 3] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "search", callCount |-> 4] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "send_email", callCount |-> 0] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "send_email", callCount |-> 1] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "send_email", callCount |-> 2] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "send_email", callCount |-> 3] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "alice"], action |-> "send_email", callCount |-> 4] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "delete_file", callCount |-> 0] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "delete_file", callCount |-> 1] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "delete_file", callCount |-> 2] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "delete_file", callCount |-> 3] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "delete_file", callCount |-> 4] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "read_file", callCount |-> 0] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "read_file", callCount |-> 1] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "read_file", callCount |-> 2] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "read_file", callCount |-> 3] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "read_file", callCount |-> 4] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "search", callCount |-> 0] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "search", callCount |-> 1] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "search", callCount |-> 2] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "search", callCount |-> 3] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "search", callCount |-> 4] :> "Allow" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "send_email", callCount |-> 0] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "send_email", callCount |-> 1] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "send_email", callCount |-> 2] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "send_email", callCount |-> 3] :> "Deny" @@
    [principal |-> [type |-> "User", id |-> "bob"], action |-> "send_email", callCount |-> 4] :> "Deny"
  )

S == INSTANCE CedarSemantics

VARIABLE done
Init == done = FALSE
Next == UNCHANGED done
Spec == Init /\ [][Next]_done

Agree == S!Agree

=============================================================================
